
# Example SensorHub configuration
server:
  host: 0.0.0.0
  port: 8080
  tls:
    enabled: false
    certfile: ./certs/server.crt
    keyfile: ./certs/server.key
    cafile: ./certs/ca.crt
    require_client_cert: false

sensors:
  - id: sim1
    kind: sim
    module: sensorhub.adapters.simulated.simulated_adapter
    class: SimulatedAdapter
    params:
      hz: 25.0
  - id: gps1
    kind: gps
    module: sensorhub.adapters.ublox_gps.ublox_adapter
    class: UbloxGPSAdapter
    params:
      port: /dev/ttyACM0
      baudrate: 9600
  # - id: imu1
  #   kind: imu
  #   module: sensorhub.adapters.generic_imu.imu_adapter
  #   class: GenericIMUAdapter
  #   params:
  #     port: /dev/ttyUSB0
  #     baudrate: 115200
  - id: livox
    kind: lidar
    module: sensorhub.adapters.livox_mid360.livox_adapter
    class: LivoxMid360Adapter
    params:
      hz: 10
  - id: rplidar
    kind: lidar2d
    module: sensorhub.adapters.rplidar_s2.rplidar_adapter
    class: RPLidarS2Adapter
    params:
      hz: 12
  - id: usb_cam1
    kind: camera
    module: sensorhub.adapters.uvc_camera.uvc_camera_adapter
    class: UVCCameraAdapter
    params:
      device: 0        # or '/dev/video0'
      width: 1280
      height: 720
      fps: 30
      quality: 80      # JPEG quality (1..100)
